#version 450

// The execution structure
layout (local_size_x = 1,local_size_y = 1, local_size_z = 1) in;

// The buffers are provided via the tensors
layout(binding = 0) buffer bufOut { float o[]; };

void main() {
    uint x = gl_GlobalInvocationID.x;
    uint y = gl_GlobalInvocationID.y;
    o[3*(512*y+x)] = float(x)/512.0f;
    o[3*(512*y+x)+1] = float(y)/512.0f;
    o[3*(512*y+x)+2] = float(x+y)/512.0f;
}